### ISSUE TITLE
Can't run gry command with rubocop v.0.48

### ISSUE THREAD

**Issue by ryoff** [pocke/gry#60]
```rb
$gry
/****/gems/gry-0.3.1/lib/gry/pilot_study.rb:11:in `analyze': undefined method `size' for nil:NilClass (NoMethodError)
        from /****/gems/gry-0.3.1/lib/gry/cli.rb:21:in `run'
        from /****/gems/gry-0.3.1/exe/gry:5:in `<top (required)>'
```

https://github.com/bbatsov/rubocop/commit/f7dc93aa213815ba4093e5b1dbe609eb38e862db#diff-769393525d94b12d89d8aeff0df0a5b9R100

https://github.com/bbatsov/rubocop/blob/v0.48.0/lib/rubocop/config.rb#L100-L103

```lib/rubocop/config.rb
@for_cop = Hash.new do |h, cop|
  qualified_cop_name = Cop::Cop.qualified_cop_name(cop, loaded_path)
  cop_options = self[qualified_cop_name] || {}
  cop_options['Enabled'] = enable_cop?(qualified_cop_name, cop_options)
  h[cop] = cop_options
end
```

Maybe `.for_cop` always return 'Enabled' key since v0.48

Therefore, `config_specified_by_user.for_cop(key).empty?` always returns "false".
https://github.com/pocke/gry/blob/master/lib/gry/rubocop_adapter.rb#L14

**Comment by pocke** [comment]
Thanks for the feedback 👍 


I've been able to reproduce this problem without `inherit_gem` option in `.rubocop.yml` only.

**Comment by pocke** [comment]
Gry 0.4.0 is released. https://rubygems.org/gems/gry/versions/0.4.0

**Comment by ryoff** [comment]
Thanks for the quick version up 🙏
